---
version: "1"  # The schema version of this config file.

ignore:  # A list of paths or files which Sourcery will ignore.
  - .devcontainer
  - .git
  - .github
  - shit*.*
  - .venv
  - .vscode

rule_settings:
  enable:
    - default
    - gpsg
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.12"

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false
